postgres-dev:
  image: postgres:latest
  ports:
   - "9932:5432"
  environment:
    POSTGRES_PASSWORD: postgres_pw
    POSTGRES_USER: postgres_user
    POSTGRES_DB: postgres_db

postgres-test:
  image: postgres:latest
  ports:
   - "9832:5432"
  environment:
    POSTGRES_PASSWORD: postgres_pw
    POSTGRES_USER: postgres_user
    POSTGRES_DB: postgres_db
